# Generated by Django 3.2.7 on 2021-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfolder',
            old_name='Folder',
            new_name='folder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userinfolder',
            unique_together={('user', 'folder')},
        ),
    ]
