# Generated by Django 3.2.7 on 2021-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211009_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfolder',
            name='role',
            field=models.IntegerField(),
        ),
    ]
