# Generated by Django 3.2.7 on 2021-10-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_arxiu_directori_usuariendirectori'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxiu',
            name='directori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.directori'),
        ),
        migrations.AddField(
            model_name='usuariendirectori',
            name='directori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.directori'),
        ),
        migrations.AddField(
            model_name='usuariendirectori',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.usuari'),
        ),
    ]
