# Generated by Django 3.2.7 on 2021-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userinfolder_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
