# Generated by Django 3.2.7 on 2021-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211007_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariendirectori',
            unique_together={('usuari', 'directori')},
        ),
    ]
