# Generated by Django 3.2.7 on 2021-10-16 13:22

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211016_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=mirage.fields.EncryptedCharField(max_length=255),
        ),
    ]
