# Generated by Django 3.2.7 on 2021-10-16 13:45

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=mirage.fields.EncryptedCharField(max_length=255),
        ),
    ]
