version: "3.9"
services:
    django:
        build: ./web
        expose:
            - 80
        environment:
            - POSTGRES_USER=web_user
            - POSTGRES_PASSWORD=GGjPs2Soo8@yk#M3
            - POSTGRES_DB=web_db
            - POSTGRES_HOST=db-web
            - POSTGRES_PORT=5432
        volumes:
            - ./web:/application
        networks:
            - django-internal
            - nginx-django
            - internal
        depends_on:
            - db-web
    db-web:
        image: "postgres:latest"
        environment:
            - POSTGRES_USER=web_user
            - POSTGRES_PASSWORD=GGjPs2Soo8@yk#M3
            - POSTGRES_DB=web_db
        volumes:
            - db-web-data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        networks:
            - django-internal
    nginx-django:
        build: ./nginx/nginx-django
        ports:
            - 8080:80
            - 8443:8443
        networks:
            - nginx-django
        depends_on:
            - django
    nginx-keycloak:
        build: ./nginx/nginx-keycloak
        ports:
            - 80:80
            - 443:443
        networks:
            - nginx-keycloak
        depends_on:
            - keycloak
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        environment:
            DB_VENDOR: MYSQL
            DB_ADDR: mysql
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            PROXY_ADDRESS_FORWARDING: 'true'
            #KEYCLOAK_LOGLEVEL: DEBUG
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "connectTimeout=30000"
        networks:
            - keycloak-internal
            - nginx-keycloak
            - internal
        expose:
            - 8080
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - ./keycloak:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        networks:
            - keycloak-internal
volumes: 
    db-web-data:
    mysql_data:
        driver: local

networks:
    internal:
    django-internal:
    keycloak-internal:
    nginx-keycloak:
    nginx-django: