version: "3.9"
services:
    nginx:
        build: .
        ports:
            - 80:80
            - 443:443
        networks:
            - web-internal
networks:
    web-internal:
        name: web-internal
